### ISSUE TITLE
Comments for contributors and content integrator

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-images#13]
I changed the structure of the TOC to match the Core infrastructure User Guide.  This lets contributors take advantage of the automated index features rather than having to build an unordered list of references. 

@ktbartholomew, @kenperkins Need to know if the content architecture off this API dev guide works for deconst, and if any changes are required.   Want to do this so we have a template to follow for all the API Dev Guides.

-  Before building, run ``make clean`` to remove any existing html output in the ``_build`` 
  directory.

- To build singlepage output, run ``make singlehtml``.  
  Output goes to _build/singlehtml/index.html.

## Root directory
Details about files in root directory
 
- [index.rst](https://github.com/rackerlabs/docs-cloud-images/edit/master/rst/dev-guide/index.rst)
  Generates the contents for the local Sphinx build.  Includes all the folders and index.rst for each. 

-  [conf.py](https://github.com/rackerlabs/docs-cloud-images/blob/master/rst/dev-guide/conf.py)
   Master file to generate the project currently set to `index.rst`

    **Note:**:  I included the following code fragments for configuration settings here for convenience. If you want to copy the source, get it from the [conf.py](https://github.com/rackerlabs/docs-cloud-images/blob/master/rst/dev-guide/conf.py) source file.

   - Make sure the ``master_doc``  value is set to ``index``

   - Added Sphinx extensions

     ```
         extensions = [
             'sphinx.ext.ifconfig',
             'sphinx.ext.todo',
             'sphinx.ext.autodoc',
             'sphinx.ext.autosummary',
             'sphinx.ext.extlinks'
        ]
    ````
   - Updated project title and copyright.

      ````      
      # General information about the project.
      project = 'Rackspace Developer Documentation
      copyright = '2015, Rackspace'
    ````
   - Added exclude patterns as needed.

     ````
      # List of patterns, relative to source directory, that match files and
      # directories to ignore when looking for source files.
     # List of patterns, relative to source directory, that match files and
    # directories to ignore when looking for source files.
       exclude_patterns = ['_build', 'samples', 'api-operations/methods*']
     ````
  - Added Rackspace external link library to support link shortcuts.
    
     ````
     # External link library
     extlinks = {
       'rax': ('http://www.rackspace.com/%s', ''),
       'rax-cloud': ('http://www.rackspace.com/cloud/%s', ''),
       'rax-docs': ('http://docs.rackspace.com/%s', ''),
       'rax-dev': ('https://developer.rackspace.com/%s', ''),
       'rax-api': ('http://api.rackspace.com/%s', ''),
       'rax-git': ('https://github.com/rackspace/%s', ''),
       'mycloud': ('https://mycloud.rackspace.com/%s', ''),
       'kc': ('http://www.rackspace.com/knowledge_center/%s', ''),
       'kc-article': ('http://www.rackspace.com/knowledge_center/article/%s', ''),
       'kc-faq': ('http://www.rackspace.com/knowledge_center/frequently-asked-question/%s', ''),
       'kc-product-faq': ('http://www.rackspace.com/knowledge_center/product-faq/%s', ''),
       'os': ('http://www.openstack.org/%s', ''),
       'os-docs': ('http://docs.openstack.org/%s', ''),
       'os-wiki': ('http://wiki.openstack.org/%s', ''),
       'git-repo': ('https://github.com/rackerlabs/docs-core-infra-user-guide/%s', ''),
       'rackerlabs': ('https://github.com/rackerlabs/%s', ''),
       'rocket': ('https://objectrocket.com/%s', '')
     }   

     ````
- Also, added values for the following parameters
    - ``htmlhelp_basename = 'RackspaceCloudApiImagesDeveloperDoc'``

    - ``latex_documents = [
  ('index', 'RackspaceCloudApiImagesDeveloperDoc.tex', 'Rackspace Cloud Images API Developer Guide',
   'Rackspace', 'manual'),
]``

  - ``man_pages = [
    ('index', 'RackspaceCloudApiImagesDeveloperDoc', 'Rackspace Cloud Images API Developer Guide',
     ['Rackspace'], 1)``

  -  ``texinfo_documents = [
  ('index', 'RackspaceCloudApiImagesDeveloperDoc', 'Rackspace Cloud Images API Developer Guide',
   'Rackspace', 'RackspaceCloudApiImagesDeveloperDoc', 'Learn about using the REST API for the Rackspace Cloud Images service.',
   'Miscellaneous'),
]``

## Overview (rst/dev-guide/overview)
- [index.rst](https://github.com/rackerlabs/docs-cloud-images/edit/master/rst/dev-guide/overview/index.rst)
  Overview landing page with toctree hidden directive to index sub-topics. Sub-topics are generated as 
  separate files. 

## Concepts
- [index.rst](https://github.com/rackerlabs/docs-cloud-images/blob/master/rst/dev-guide/concepts/index.rst)
  Concepts landing page with directive to index sub-topics.  All sub-topics are compiled into a single 
  file [concepts-topics.rst](https://github.com/rackerlabs/docs-cloud-images/edit/master/rst/dev- guide/concepts/concepts-topics.rst)

## General API information
- [index.rst](https://github.com/rackerlabs/docs-cloud-images/blob/master/rst/dev-guide/general-api-info/index.rst)
 General API Info landing page with directive to index sub-topics. Sub-topics generated as separate files. 

## API operations structure:  (``rst/dev-guide/api-operations``)

-  [index.rst](https://github.com/rackerlabs/docs-cloud-images/edit/master/rst/dev-guide/api-operations/index.rst)
   Uses the toctree directive to index all of the resource landing pages for the API operations.

-  *Resource type landing page*
   Provides a brief intro for the API resource type and uses the .. include:: directive to create a single output page that compiles the content from the resource landing page source file and all associated API method source files.  **Example:** [Images operations](https://github.com/rackerlabs/docs-cloud-images/edit/master/rst/dev-guide/api-operations/images-operations.rst)

### API operation method pages (``rst/dev-guide/api-operations/methods``) 
All API operation method documentation is in the ``methods`` directory.  These files are integrated into the build by using the ``include`` directive.  This structure allows us to separate the methods from the landing pages, making it easier to see the structure of the content.  It also separates the WADL-generated content from the resource landing pages. 

Each method has reference id at the top. These were automatically generated by the WADL2RST conversion. **Example:** ```.. _delete-delete-image-images-image-id:``` [Delete image](https://github.com/rackerlabs/docs-cloud-images/edit/master/rst/dev-guide/api-operations/delete-delete-image-images-image-id.rst).  You can edit them to remove duplicate words, and make them match the method title.   

Examples from Cloud Images: < https://github.com/rackerlabs/docs-cloud-images/tree/master/rst/dev-guide/api-operations/methods>`_

**Comment by ktbartholomew** [comment]
Currently, this will not work with the Sphinx preparer, because it was written explicitly with multi-page documents in mind (it extends the builder used in `make html` and adds special deconst stuff on top of that).

In order to submit the content to deconst in a way that produces output similar to that of `build singlehtml`, we have to write an additional builder that instead extends the `singlehtml` builder. This is a pretty significant undertaking and could take a few days to get right.  I'll provide updates as I have them.

**Comment by meker12** [comment]
I merged the pull request with the conf.py update for deconst.   

Also made additional changes to get rid of duplicate errors caused by included api-operations files, and updated refids to avoid duplicating names in URL -- ```api-operations/api-operations-image-sharing```

Let me know if anything else is required for the Nexus/UX integration release.

**Comment by meker12** [comment]
@ktbartholomew created the preparer and a template for singlehtml output.  Thank you!
