### ISSUE TITLE
RST Devguide has some broken links

### ISSUE THREAD

**Issue by masthalter** [rackerlabs/docs-cloud-images#25]
1. RBAC: Assigning Roles to Account Users has two broken links:

Assign roles to account users -- this should link to: 
http://docs.rackspace.com/auth/api/v2.0/auth-client-devguide/content/PUT_addUserRole__v2.0_users__userId__roles_OS-KSADM__roleid__Role_Calls.html

Delete roles from account users -- this should link to:
http://docs.rackspace.com/auth/api/v2.0/auth-client-devguide/content/DELETE_deleteUserRole__v2.0_users__userId__roles_OS-KSADM__roleid__Role_Calls.html

2. List images operation has an broken link for the attribute images.status. 
For possible image statuses, see ` 1.4.1. Image statuses <http://docs.rackspace.com/images/api/v2/ci- devguide/content/image-statuses.html>`.

Notice how the end part of the URL is not underlined in the RST doc, so the link is incorrect.

It appears that this should link to your topic "Image statuses" in the RST Devguide.

3. Get image details has a broken link for the attribute status.
Same link is broken as above.

4. Update image has a broken link for the attribute status.
Same link is broken as above.

5. Tasks to import image has a broken link for the attribute status.
Same link is broken as above.

6. Tasks to export image has a broken link for the attribute status.
Same link is broken as above.

**Comment by catlook** [comment]
Fixed!  Pushing and getting republished.  Thanks, Mike!

**Comment by catlook** [comment]
opps..closing now.
