### ISSUE TITLE
Dangling comma in Update an image member

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/docs-cloud-images#43]
In the first sentence of the "Update an image member" section, there's a semi-random comma in this sentence:

"If you send a request, outside of the Cloud Images API to an image producer asking for access to an image..."

This should read:

"If you send a request, outside of the Cloud Images API, to an image producer asking for access to an image..."

OR

"If you send a request outside of the Cloud Images API to an image producer asking for access to an image..."

**Comment by catlook** [comment]
done.  can't have too many commas!
