### ISSUE TITLE
Missing note in Update an image member section

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/docs-cloud-images#44]
On docs.rackspace there's a note about image member status that is missing from the converted doc.

![screen shot 2015-12-08 at 9 10 15 am](https://cloud.githubusercontent.com/assets/12717324/11658983/85858f8c-9d8b-11e5-9142-6c80df9102c2.png)

Not sure if this was left out intentionally, but thought I would mention it.

**Comment by catlook** [comment]
done
