### ISSUE TITLE
enable data collection for Google Analytics

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-cloud-images#5]
in pom.xml, change every occurrence (I see 3) of 
" enableGoogleAnalytics 0 /enableGoogleAnalytics "
to 
" enableGoogleAnalytics 1 /enableGoogleAnalytics"

If you make this change before March 1, a full month of Cloud Images usage data can be included in the March 2015 monthly report. 

(angle brackets around enableGooglAnalytics disappear when I save the comment; you'll find them in pom.xml)

**Comment by catlook** [comment]
done.  will publish later this week.  thanks!
