### ISSUE TITLE
generated version on the rackspace docs displays URL instead of PNG image

### ISSUE THREAD

**Issue by ostackbrian** [rackerlabs/docs-cloud-images#66]
The page
    https://developer.rackspace.com/docs/cloud-images/v2/developer-guide/#image-sharing
just displays a URL instead of the image.  The reference is at line 184 in api-docs/concepts.rst ; it displays fine in the "normal view" here in GitHub, so it doesn't look like it's an image problem.

**Comment by kylelaffoon** [comment]
Corrected image reference and it now presents image correctly.
