### ISSUE TITLE
bad ref in import task doc

### ISSUE THREAD

**Issue by ostackbrian** [rackerlabs/docs-cloud-images#67]
:ref:` Rackspace terms of service <TOS>` displays as unrendered, both in github and at https://developer.rackspace.com/docs/cloud-images/v2/developer-guide/#task-to-import-image

**Comment by catlook** [comment]
Thanks...let me see what I can do about this!!

**Comment by catlook** [comment]
Explanation: We no longer include the TOS in the individual API guides, so I've changed the language to reflect that in this section.  Good catch!

**Comment by catlook** [comment]
done!
