### ISSUE TITLE
Refactor Images v2 QE

### ISSUE THREAD

**Issue by catlook** [rackerlabs/docs-cloud-images#87]
# Refactor API Guide: QE checklist

Use the following checklist to verify that API guide refactoring for each service. If you have questions, open a [docs-common issue](https://github.com/rackerlabs/docs-common/issues/new).  

Do the QE check against the PR submitted to the master repo.  Ask the person who did the refactoring to make you a collaborator on their fork in case you want to submit a PR to correct something. 

When you build the refactored Sphinx project, use the ``make clean html`` command to build chunked content. 

- [x] Review the [Strider build log](https://build.developer.rackspace.com/) for errors. Notify author about any issues.
- [x] Check for broken links.
- [x] Verify that navigation matches the [API Guide template](https://staging.developer.rackspace.com/staging.horse/build-2ecafb8a99/docs/api-doc-template/).
- [x] Check the *API reference* section to verify that the methods for each resource are in a single topic.
- [x] Check the *General API information* topics to make sure they match the common content where possible.
- [x] Check the *Authentication* topic in the Getting started section to make sure it matches the [common template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/getting-started/authenticate.rst).
- [x] Check ``conf.py`` to make sure it has the updates from the 
       [template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/conf.py).
- [x] Verify that you can [build locally from source](https://github.com/rackerlabs/docs-rackspace/blob/master/doc/tools/build-from-source.rst).

**Comment by cyrichardson** [comment]
@catlook noted that she is leaving in the glossary for now but may move that info to a concepts file.

**Comment by cyrichardson** [comment]
Broken links reported to Cat via Slack. There is some question about those going to Identity and RBAC stuff. (But those links on developer.rackspace.com for CBS, Rackspace CDN, and Cloud Backup v1 are currently working.) Margaret is investigating.

**Comment by cyrichardson** [comment]
Closing since all checks are been completed, even though there is an investigation going on about links. But I think that may be another issue.
