### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by BenjamenMeyer** [rackerlabs/docs-cloud-images#94]
The OpenStack links have changed a bit and at least one no longer points in the right place - http://docs.openstack.org/trunk/openstack-compute/admin/content/adding-images.html - this probably needs to point at some OpenStack Glance documentation; it redirects to the OpenStack Compute Admin documentation which has no information on adding images any longer AFAICT.

**Comment by cyrichardson** [comment]
@BenjamenMeyer, Thank you! 

@catlook Did you want to handle this issue, or would you like for me to handle it?

**Comment by catlook** [comment]
got it!

**Comment by catlook** [comment]
@BenjaminMeyer, as it turns out, the bad link you identified was part of the response coming from the API call, not something I can just change.  However, when I tested the operation, the "os_distro" component wasn't even part of the response, so I've removed it from the documentation.  Thanks!

**Comment by BenjamenMeyer** [comment]
@catlook interesting since I'm pulling the `os_distro` value for a project and that's working just fine.

**Comment by catlook** [comment]
Hmmm.  Let me see what I can find!

**Comment by catlook** [comment]
Does this help?  https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html

**Comment by BenjamenMeyer** [comment]
yes, that would be perfect!

**Comment by catlook** [comment]
Oh i did find this for you, already in the doc:  https://developer.rackspace.com/docs/cloud-images/v2/getting-started/concepts/#image-properties

**Comment by BenjamenMeyer** [comment]
cool - IIRC, i think the original thing was against Cloud Servers? I can't remember...
thanks for finding these links. Close out as you like. Thanks!
